# Secret scanning template (Gate C / ADR 013 must-have C4)
# Uses gitleaks CLI (no org license required for the GitHub Action).

name: Secret Scan

on:
  workflow_call:

jobs:
  gitleaks:
    runs-on:
      - self-hosted
      - linux
      - x64
      - roamkit
      - docker
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        run: |
          docker run --rm -v "$PWD:/path" zricethezav/gitleaks:v8.24.2 \
            detect --source=/path --verbose --redact
